// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FerreteriaEntities.Entities;

public partial class tbClientes
{
    public int Clie_Id { get; set; }

    public string Clie_DNI { get; set; }

    public string Clie_Nombre { get; set; }

    public string Clie_Apellido { get; set; }

    public string Clie_Sexo { get; set; }

    public int EsCv_Id { get; set; }

    public string Muni_Codigo { get; set; }

    public string Clie_Direccion { get; set; }

    public int Usua_Creacion { get; set; }

    public DateTime Feca_Creacion { get; set; }

    public int? Usua_Modificacion { get; set; }

    public DateTime? Feca_Modificacion { get; set; }

    public bool? Clie_Estado { get; set; }

    public virtual tbEstadosCiviles EsCv { get; set; }

    public virtual tbMunicipios Muni_CodigoNavigation { get; set; }

    public virtual tbUsuarios Usua_CreacionNavigation { get; set; }

    public virtual tbUsuarios Usua_ModificacionNavigation { get; set; }

    public virtual ICollection<tbVentas> tbVentas { get; set; } = new List<tbVentas>();
}