// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FerreteriaEntities.Entities;

public partial class tbComprasDetalles
{
    public int CpDe_Id { get; set; }

    public int Comp_Id { get; set; }

    public int Prod_Id { get; set; }

    public int CpDe_Cantidad { get; set; }

    public double CpDe_Precio { get; set; }

    public int Usua_Creacion { get; set; }

    public DateTime Feca_Creacion { get; set; }

    public int? Usua_Modificacion { get; set; }

    public DateTime? Feca_Modificacion { get; set; }

    public bool? CpDe_Estado { get; set; }

    public virtual tbCompras Comp { get; set; }

    public virtual tbProductos Prod { get; set; }

    public virtual tbUsuarios Usua_CreacionNavigation { get; set; }

    public virtual tbUsuarios Usua_ModificacionNavigation { get; set; }
}