// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace FerreteriaEntities.Entities;

public partial class tbUsuarios
{
    public int Usua_Id { get; set; }

    public string Usua_Nombre { get; set; }

    public string Usua_Clave { get; set; }

    public int Empl_Id { get; set; }

    [NotMapped]
    public string Empl_NombreCompleto { get; set; }

    public int Role_Id { get; set; }

    [NotMapped]
    public string Role_Descripcion { get; set; }

    public bool? Usua_EsAdmin { get; set; }

    public int Usua_Creacion { get; set; }

    public DateTime Feca_Creacion { get; set; }

    public int? Usua_Modificacion { get; set; }

    public DateTime? Feca_Modificacion { get; set; }

    public bool? Usua_Estado { get; set; }

    public virtual tbEmpleados Empl { get; set; }

    public virtual tbRoles Role { get; set; }

    public virtual ICollection<tbCargos> tbCargosUsua_CreacionNavigation { get; set; } = new List<tbCargos>();

    public virtual ICollection<tbCargos> tbCargosUsua_ModificacionNavigation { get; set; } = new List<tbCargos>();

    public virtual ICollection<tbCategorias> tbCategoriasUsua_CreacionNavigation { get; set; } = new List<tbCategorias>();

    public virtual ICollection<tbCategorias> tbCategoriasUsua_ModificacionNavigation { get; set; } = new List<tbCategorias>();

    public virtual ICollection<tbClientes> tbClientesUsua_CreacionNavigation { get; set; } = new List<tbClientes>();

    public virtual ICollection<tbClientes> tbClientesUsua_ModificacionNavigation { get; set; } = new List<tbClientes>();

    public virtual ICollection<tbComprasDetalles> tbComprasDetallesUsua_CreacionNavigation { get; set; } = new List<tbComprasDetalles>();

    public virtual ICollection<tbComprasDetalles> tbComprasDetallesUsua_ModificacionNavigation { get; set; } = new List<tbComprasDetalles>();

    public virtual ICollection<tbCompras> tbComprasUsua_CreacionNavigation { get; set; } = new List<tbCompras>();

    public virtual ICollection<tbCompras> tbComprasUsua_ModificacionNavigation { get; set; } = new List<tbCompras>();

    public virtual ICollection<tbDepartamentos> tbDepartamentosUsua_CreacionNavigation { get; set; } = new List<tbDepartamentos>();

    public virtual ICollection<tbDepartamentos> tbDepartamentosUsua_ModificacionNavigation { get; set; } = new List<tbDepartamentos>();

    public virtual ICollection<tbEmpleados> tbEmpleadosUsua_CreacionNavigation { get; set; } = new List<tbEmpleados>();

    public virtual ICollection<tbEmpleados> tbEmpleadosUsua_ModificacionNavigation { get; set; } = new List<tbEmpleados>();

    public virtual ICollection<tbEstadosCiviles> tbEstadosCivilesUsua_CreacionNavigation { get; set; } = new List<tbEstadosCiviles>();

    public virtual ICollection<tbEstadosCiviles> tbEstadosCivilesUsua_ModificacionNavigation { get; set; } = new List<tbEstadosCiviles>();

    public virtual ICollection<tbMarcas> tbMarcasUsua_CreacionNavigation { get; set; } = new List<tbMarcas>();

    public virtual ICollection<tbMarcas> tbMarcasUsua_ModificacionNavigation { get; set; } = new List<tbMarcas>();

    public virtual ICollection<tbMedidas> tbMedidasUsua_CreacionNavigation { get; set; } = new List<tbMedidas>();

    public virtual ICollection<tbMedidas> tbMedidasUsua_ModificacionNavigation { get; set; } = new List<tbMedidas>();

    public virtual ICollection<tbMunicipios> tbMunicipiosUsua_CreacionNavigation { get; set; } = new List<tbMunicipios>();

    public virtual ICollection<tbMunicipios> tbMunicipiosUsua_ModificacionNavigation { get; set; } = new List<tbMunicipios>();

    public virtual ICollection<tbPantallas> tbPantallasUsua_CreacionNavigation { get; set; } = new List<tbPantallas>();

    public virtual ICollection<tbPantallas> tbPantallasUsua_ModificacionNavigation { get; set; } = new List<tbPantallas>();

    public virtual ICollection<tbProductos> tbProductosUsua_CreacionNavigation { get; set; } = new List<tbProductos>();

    public virtual ICollection<tbProductos> tbProductosUsua_ModificacionNavigation { get; set; } = new List<tbProductos>();

    public virtual ICollection<tbProveedores> tbProveedoresUsua_CreacionNavigation { get; set; } = new List<tbProveedores>();

    public virtual ICollection<tbProveedores> tbProveedoresUsua_ModificacionNavigation { get; set; } = new List<tbProveedores>();

    public virtual ICollection<tbRoles> tbRolesUsua_CreacionNavigation { get; set; } = new List<tbRoles>();

    public virtual ICollection<tbRoles> tbRolesUsua_ModificacionNavigation { get; set; } = new List<tbRoles>();

    public virtual ICollection<tbSucursales> tbSucursalesUsua_CreacionNavigation { get; set; } = new List<tbSucursales>();

    public virtual ICollection<tbSucursales> tbSucursalesUsua_ModificacionNavigation { get; set; } = new List<tbSucursales>();

    public virtual ICollection<tbVentasDetalles> tbVentasDetallesUsua_CreacionNavigation { get; set; } = new List<tbVentasDetalles>();

    public virtual ICollection<tbVentasDetalles> tbVentasDetallesUsua_ModificacionNavigation { get; set; } = new List<tbVentasDetalles>();

    public virtual ICollection<tbVentas> tbVentasUsua_CreacionNavigation { get; set; } = new List<tbVentas>();

    public virtual ICollection<tbVentas> tbVentasUsua_ModificacionNavigation { get; set; } = new List<tbVentas>();
}