// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FerreteriaEntities.Entities;

public partial class tbVentas
{
    public int Vent_Id { get; set; }

    public int Clie_Id { get; set; }

    public DateOnly Vent_Fecha { get; set; }

    public int Usua_Creacion { get; set; }

    public DateTime Feca_Creacion { get; set; }

    public int? Usua_Modificacion { get; set; }

    public DateTime? Feca_Modificacion { get; set; }

    public bool? Vent_Estado { get; set; }

    public virtual tbClientes Clie { get; set; }

    public virtual tbUsuarios Usua_CreacionNavigation { get; set; }

    public virtual tbUsuarios Usua_ModificacionNavigation { get; set; }

    public virtual ICollection<tbVentasDetalles> tbVentasDetalles { get; set; } = new List<tbVentasDetalles>();
}